#对于rabbitMQ的支持
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672       #15672是管理端口
    username: guest
    password: guest
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
server:
  port: 8080